import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

/**
 * SyncEngine manages the background synchronization of Antigravity conversation threads
 * between the local user's ~/.gemini/antigravity folder and the workspace-specific
 * .antigravity/gemini_sync folder.
 * Sync is purely additive and bidirectional based on file modification times.
 */
export class SyncEngine {

    private readonly _context: vscode.ExtensionContext;

    constructor(context: vscode.ExtensionContext) {
        this._context = context;
    }

    /**
     * Gets the path to the user's global Gemini directory.
     * @returns {string} The absolute path to ~/.gemini/antigravity.
     */
    private getGlobalGeminiPath(): string {
        const homeDir = process.env.USERPROFILE || process.env.HOME || '';
        return path.join(homeDir, '.gemini', 'antigravity');
    }

    /**
     * Gets the target sync directory within the current workspace.
     * @returns {string | null} The workspace sync path, or null if no workspace is active.
     */
    private getWorkspaceSyncPath(): string | null {
        const workspaceFolders = vscode.workspace.workspaceFolders;
        if (!workspaceFolders || workspaceFolders.length === 0) {
            return null;
        }
        return path.join(workspaceFolders[0].uri.fsPath, '.antigravity', 'gemini_sync');
    }

    /**
     * Automatically drops a README in the workspace root to ensure future developers
     * understand what these inert files are.
     */
    private async writeSafetyReadme(workspacePath: string): Promise<void> {
        try {
            const readmePath = path.join(workspacePath, 'README-_DONT_PANIC.txt');
            const readmeContent = `AUTO-CONTINUE PLUS PLUS: OFFLINE SYNC DIRECTORY
===============================================

DON'T PANIC!
This folder was automatically generated by the 'Auto-Continue Plus Plus' VS Code extension.
It contains copied markdown and json files representing the AI conversation history ("Brain") of the user who exported them.

IS IT SAFE TO DELETE?
Yes. If you no longer use Auto-Continue, or if you do not care about keeping your AI chatting history synced to this specific workspace, you can safely delete this entire '.antigravity/' directory wrapper. It will not break your actual source code.

WHY DOES IT EXIST?
By default, VS Code AI agents store their chat history deep in your local computer's home directory (~/.gemini or ~/.cline). This prevents that history from syncing across computers if you use Dropbox, Git, or a remote server. This seamless sync allowed those conversations to roam with the project.
`;
            if (!fs.existsSync(workspacePath)) {
                await fs.promises.mkdir(workspacePath, { recursive: true });
            }
            if (!fs.existsSync(readmePath)) {
                await fs.promises.writeFile(readmePath, readmeContent, 'utf8');
            }
        } catch (e) {
            console.error('[SyncEngine] Failed to write Safety README', e);
        }
    }

    /**
     * Helper to recursively get all files in a directory using Promises
     */
    private async getAllFiles(dirPath: string, arrayOfFiles: string[] = [], relativePath: string = ''): Promise<string[]> {
        if (!fs.existsSync(dirPath)) return arrayOfFiles;

        const files = await fs.promises.readdir(dirPath);

        for (const file of files) {
            const absolutePath = path.join(dirPath, file);
            const relPathStr = path.join(relativePath, file);
            const stat = await fs.promises.stat(absolutePath);

            if (stat.isDirectory()) {
                arrayOfFiles = await this.getAllFiles(absolutePath, arrayOfFiles, relPathStr);
            } else {
                arrayOfFiles.push(relPathStr);
            }
        }

        return arrayOfFiles;
    }

    /**
     * Compares two directories and additively syncs newer versions of files using async fs.
     * Missing files are copied. Older files are overwritten by newer equivalents.
     * Deletions on one side do NOT cause deletions on the other (Additive only).
     */
    private async mergeDirectories(dirA: string, dirB: string): Promise<void> {
        if (!fs.existsSync(dirA)) await fs.promises.mkdir(dirA, { recursive: true });
        if (!fs.existsSync(dirB)) await fs.promises.mkdir(dirB, { recursive: true });

        const filesA = await this.getAllFiles(dirA);
        const filesB = await this.getAllFiles(dirB);

        // Map relative path to absolute paths
        const setA = new Set(filesA);
        const setB = new Set(filesB);

        // Sync A -> B
        for (const fileRel of filesA) {
            const pathA = path.join(dirA, fileRel);
            const pathB = path.join(dirB, fileRel);

            if (!setB.has(fileRel)) {
                // File exists in A but not B: Copy A -> B
                const targetDir = path.dirname(pathB);
                if (!fs.existsSync(targetDir)) await fs.promises.mkdir(targetDir, { recursive: true });
                await fs.promises.copyFile(pathA, pathB);
            } else {
                // File exists in both: Check mtime
                const statA = await fs.promises.stat(pathA);
                const statB = await fs.promises.stat(pathB);

                // If A is strictly newer, overwrite B
                if (statA.mtimeMs > statB.mtimeMs) {
                    await fs.promises.copyFile(pathA, pathB);
                }
            }
        }

        // Sync B -> A
        for (const fileRel of filesB) {
            const pathA = path.join(dirA, fileRel);
            const pathB = path.join(dirB, fileRel);

            if (!setA.has(fileRel)) {
                // File exists in B but not A: Copy B -> A
                const targetDir = path.dirname(pathA);
                if (!fs.existsSync(targetDir)) await fs.promises.mkdir(targetDir, { recursive: true });
                await fs.promises.copyFile(pathB, pathA);
            } else {
                // File exists in both: Check mtime
                const statA = await fs.promises.stat(pathA);
                const statB = await fs.promises.stat(pathB);

                // If B is strictly newer, overwrite A
                if (statB.mtimeMs > statA.mtimeMs) {
                    await fs.promises.copyFile(pathB, pathA);
                }
            }
        }
    }

    /**
     * Performs a seamless, additive, bidirectional synchronization
     * between ~/.gemini/antigravity and [workspace]/.antigravity/gemini_sync
     */
    public async runContinuousSync(): Promise<void> {
        try {
            const globalPath = this.getGlobalGeminiPath();
            const workspacePath = this.getWorkspaceSyncPath();

            if (!workspacePath) return; // Silent return if no workspace

            // Ensure directories exist before attempting to merge
            if (!fs.existsSync(globalPath)) {
                await fs.promises.mkdir(globalPath, { recursive: true });
            }
            if (!fs.existsSync(workspacePath)) {
                await fs.promises.mkdir(workspacePath, { recursive: true });
            }

            // Perform Bidirectional merge
            await this.mergeDirectories(globalPath, workspacePath);

            // Drop safety README if missing
            await this.writeSafetyReadme(workspacePath);

        } catch (error: any) {
            console.error('[SyncEngine] Continuous Sync Failed', error);
        }
    }
}
