import { AgentTaskState, AgentTaskResult, IBoltOn } from '../boltons/types';

/**
 * Validates inputs and outputs of Bolt-Ons based on Zero-Trust principles.
 * Ensures the pre-conditions and post-conditions are strictly enforced
 * before handing state back to the Swarm Manager, avoiding "quiet failures".
 */
export class ZeroTrustValidator {
    /**
     * Enforces the pre-conditions of a Bolt-On before execution.
     * Validates that the state is well-formed and that the Bolt-On itself accepts it.
     *
     * @param boltOn The Bolt-On to validate against.
     * @param state The input state provided by the Swarm Manager.
     * @throws {Error} if validation fails with loud, descriptive errors.
     */
    public validateExecutionStart(boltOn: IBoltOn, state: AgentTaskState): void {
        console.log(`[ZeroTrustValidator] Validating pre-conditions for Bolt-On '${boltOn.id}'...`);

        // 1. Validate the fundamental structure of the state
        if (!state) {
            throw new Error(`[ZeroTrustValidator] Critical Error: Received null or undefined state for Bolt-On '${boltOn.id}'.`);
        }
        if (!state.taskId || state.taskId.trim() === '') {
            throw new Error(`[ZeroTrustValidator] Critical Error: Task state for Bolt-On '${boltOn.id}' is missing a valid 'taskId'.`);
        }

        // 2. Delegate to the Bolt-On's specific pre-condition checks
        try {
            boltOn.validatePreConditions(state);
        } catch (error: unknown) {
            const errorMsg = error instanceof Error ? error.message : String(error);
            // We throw a loud error instead of swallowing it to enforce strict routing contracts
            throw new Error(`[ZeroTrustValidator] Pre-condition failure for Bolt-On '${boltOn.id}' on Task '${state.taskId}'. Details: ${errorMsg}`);
        }

        console.log(`[ZeroTrustValidator] Pre-conditions passed for Bolt-On '${boltOn.id}'.`);
    }

    /**
     * Enforces the post-conditions of a Bolt-On after execution.
     * Validates that the result is strictly typed and meets the Bolt-On's expectations.
     *
     * @param boltOn The Bolt-On that executed the task.
     * @param result The output result generated by the Bolt-On.
     * @throws {Error} if the result is invalid or violates post-conditions.
     */
    public validateExecutionEnd(boltOn: IBoltOn, result: AgentTaskResult): void {
        console.log(`[ZeroTrustValidator] Validating post-conditions for Bolt-On '${boltOn.id}'...`);

        // 1. Validate fundamental structure of the result
        if (!result) {
            throw new Error(`[ZeroTrustValidator] Critical Error: Bolt-On '${boltOn.id}' returned a null or undefined result.`);
        }
        if (typeof result.success !== 'boolean') {
            throw new Error(`[ZeroTrustValidator] Critical Error: Result from Bolt-On '${boltOn.id}' is missing a valid boolean 'success' flag.`);
        }
        if (typeof result.message !== 'string') {
            throw new Error(`[ZeroTrustValidator] Critical Error: Result from Bolt-On '${boltOn.id}' is missing a descriptive 'message' string.`);
        }

        // 2. If it claims success but provides an error detail, or vice versa, flag it
        if (result.success && result.errorDetails) {
            throw new Error(`[ZeroTrustValidator] Logic Error: Bolt-On '${boltOn.id}' returned success=true but included errorDetails ('${result.errorDetails}').`);
        }
        if (!result.success && !result.errorDetails) {
             throw new Error(`[ZeroTrustValidator] Logic Error: Bolt-On '${boltOn.id}' returned success=false but did not provide errorDetails.`);
        }

        // 3. Delegate to the Bolt-On's specific post-condition checks
        try {
            boltOn.validatePostConditions(result);
        } catch (error: unknown) {
            const errorMsg = error instanceof Error ? error.message : String(error);
            throw new Error(`[ZeroTrustValidator] Post-condition failure for Bolt-On '${boltOn.id}'. The agent likely hallucinated success or failed to fulfill the contract. Details: ${errorMsg}`);
        }

        console.log(`[ZeroTrustValidator] Post-conditions passed for Bolt-On '${boltOn.id}'.`);
    }
}
